### ISSUE TITLE
Error running on Windows

### ISSUE THREAD

**Issue by kzantow** [jonjaques/gulp-runner#2]
Trying to use this on Windows results in:

```
internal/child_process.js:302
    throw errnoException(err, 'spawn');
    ^

Error: spawn UNKNOWN
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)
    at Object.exports.spawn (child_process.js:380:9)
    at GulpRunner.run (<path>\node_modules\gulp-runner\index.js:34:20)
    ...
```

**Comment by kzantow** [comment]
@jonjaques thanks much!
